title: Jiayi Chen's Homepage
page-top-title: Jiayi Chen
top-section-bg-text: INDUSTRAL ENGINEERING
home-subtitle: Jiayi Chen&ensp;|&ensp;陈佳翌
copyright-text: '&copy; Jiayi Chen 2022-2026. All Rights Reserved.'
